### ISSUE TITLE
Usage in my own project?

### ISSUE THREAD

**Issue by spide-r** [ewaszoeke/WebsiteColorPicker#1]
Hey! I was looking around for a cool color picker and I like your project, but there isn't any license. Am I able to use this in my own projects? If so, I would suggest to add a license to make it clear that people can use your work. I recommend the MIT license but you can find others at https://choosealicense.com/

**Comment by ewaszoeke** [comment]
Hi, it's funny that you found this small project :) I needed a color picker that shows me the corresponding integer-value of a hex-value, so I build one in Javascript/HTML. I added a short description and the MIT-License. Have fun.
